import type { Metadata } from "next";
import ClientRootLayout from "./client-layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={``}>
        <ClientRootLayout>{children}</ClientRootLayout>
      </body>
    </html>
  );
}
